version: '3.5'

services:
  mysql:
    image: mysql:5.7.38-debian
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "13306:3306"
    environment:
      MYSQL_DATABASE: nodebb
      MYSQL_ROOT_PASSWORD: test
    volumes:
      - mysql-data:/var/lib/mysql
      - ./assets/test/mysql/init:/docker-entrypoint-initdb.d
  postgres:
    image: postgres:10.21-alpine
    restart: unless-stopped
    ports:
      - "15432:5432"
    environment:
      POSTGRES_PASSWORD: test
    volumes:
      - postgres-data:/var/lib/postgresql/data
  mssql:
    image: mcr.microsoft.com/azure-sql-edge:1.0.6
    restart: unless-stopped
    environment:
      ACCEPT_EULA: 'Y'
      MSSQL_SA_PASSWORD: 'StrongPassword@123'
    ports:
      - "11433:1433"
    volumes:
      - azure-sql-data:/var/opt/mssql

volumes:
  mysql-data:
  postgres-data:
  azure-sql-data:
